import { useState } from 'react';
import { useStore } from '../store/useStore';
import { Compass, GraduationCap, ClipboardList, Briefcase, Mail, CheckCircle2 } from 'lucide-react';

export default function RoadmapTab() {
  const { activeResult } = useStore();
  const { roadmap } = activeResult;

  const mTabs = [
    { id: 't30', label: '30 Days', step: roadmap.plan30Days },
    { id: 't60', label: '60 Days', step: roadmap.plan60Days },
    { id: 't90', label: '90 Days', step: roadmap.plan90Days },
    { id: 't6m', label: '6 Months', step: roadmap.plan6Months },
    { id: 't12', label: '12 Months', step: roadmap.plan12Months }
  ];

  const [activeSegmentId, setActiveSegmentId] = useState('t30');
  const activeStep = mTabs.find(t => t.id === activeSegmentId)?.step || roadmap.plan30Days;

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      
      {/* 1. Overview Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="heading-font text-xl md:text-2xl font-bold text-white">Interactive Career Roadmap</h2>
          <p className="text-slate-400 text-xs md:text-sm mt-1">
            Progressive curriculum generated by Gemini mapping necessary technical levels and accreditations.
          </p>
        </div>
      </div>

      {/* 2. Timeline Steps Switcher (Horizontal Pipeline) */}
      <div className="flex flex-wrap gap-2 text-xs border-b border-white/5 pb-4">
        {mTabs.map((item) => (
          <button
            key={item.id}
            onClick={() => setActiveSegmentId(item.id)}
            className={`px-4 py-3 rounded-2xl border font-bold flex flex-col gap-1 text-left min-w-[120px] transition duration-200 ${
              activeSegmentId === item.id
                ? 'bg-indigo-650/15 border-indigo-500 text-indigo-300 shadow-lg shadow-indigo-600/5'
                : 'border-white/5 bg-slate-900/40 hover:bg-slate-900 text-slate-400 hover:text-white'
            }`}
          >
            <span className="text-[10px] block font-semibold text-slate-500">{item.step.duration}</span>
            <span className="text-sm">{item.label}</span>
          </button>
        ))}
      </div>

      {/* 3. Splendid Master Milestone Layout (Vertical Breakdown Panels) */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Core Description Left Block */}
        <div className="glass-panel p-6 rounded-3xl space-y-4 lg:col-span-1 flex flex-col justify-between bg-gradient-to-b from-slate-900/60 to-slate-950/40">
          <div className="space-y-3">
            <div className="flex justify-between items-center text-xs font-bold text-slate-500 uppercase tracking-widest">
              <span>Phase Objective</span>
              <span className="px-1.5 py-0.5 rounded border border-emerald-500/25 bg-emerald-500/10 text-emerald-400 text-[8.5px] font-black tracking-normal" title="Confidence rated for standard career execution accuracy.">
                AI CONF: 92%
              </span>
            </div>
            <h3 className="heading-font text-lg font-black text-white">{activeStep.title}</h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              This block concentrates heavily on constructing foundational blocks, completing certification validations, and optimizing profile scopes or networking channels.
            </p>
          </div>

          <div className="p-4 rounded-2xl bg-indigo-505/5 border border-indigo-500/10 flex items-start gap-3 mt-4">
            <Compass className="h-5 w-5 text-indigo-400 shrink-0 mt-0.5 animate-spin" style={{ animationDuration: '6s' }} />
            <div>
              <span className="text-[11px] font-bold text-indigo-300 uppercase tracking-wider block">Advisor Tip</span>
              <p className="text-[11px] text-slate-400 leading-normal">
                Executing portfolio milestones and code challenges within this phase increases target salary outcomes and interview odds.
              </p>
            </div>
          </div>
        </div>

        {/* Action Items Categorized (Right Panels) */}
        <div className="lg:col-span-2 grid grid-cols-1 sm:grid-cols-2 gap-4">
          
          {/* Box 1: Skills & Certifications */}
          <div className="glass-panel p-5 rounded-2xl space-y-3">
            <div className="flex items-center gap-2">
              <GraduationCap className="h-4 w-4 text-cyan-400" />
              <h4 className="heading-font text-sm font-bold text-white">Knowledge Hub & Certs</h4>
            </div>
            <div className="space-y-4">
              <div>
                <span className="text-[10px] font-bold text-slate-500 uppercase block mb-1.5">Focus Skills:</span>
                <div className="flex flex-wrap gap-1.5">
                  {activeStep.skillsToLearn.map((skill, i) => (
                    <span key={i} className="text-[10px] px-2 py-1 bg-slate-900 rounded-lg text-slate-300 font-medium">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>
              {activeStep.certifications && activeStep.certifications.length > 0 && (
                <div>
                  <span className="text-[10px] font-bold text-slate-500 uppercase block mb-1.5">Target Credentials:</span>
                  <ul className="space-y-1.5">
                    {activeStep.certifications.map((cert, i) => (
                      <li key={i} className="text-xs text-slate-300 flex items-start gap-1.5 font-medium">
                        <CheckCircle2 className="h-3.5 w-3.5 text-cyan-400 shrink-0 mt-0.5" />
                        {cert}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>

          {/* Box 2: Portfolio & Dynamic Projects */}
          <div className="glass-panel p-5 rounded-2xl space-y-3">
            <div className="flex items-center gap-2">
              <ClipboardList className="h-4 w-4 text-emerald-400" />
              <h4 className="heading-font text-sm font-bold text-white">Dynamic Portfolios</h4>
            </div>
            <div className="space-y-3 text-xs leading-relaxed text-slate-300 font-medium">
              <div>
                <span className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Target Project:</span>
                {activeStep.projects.map((proj, i) => (
                  <p key={i} className="p-2.5 bg-slate-900/60 rounded-xl border border-white/5 font-semibold text-white">
                    {proj}
                  </p>
                ))}
              </div>
              <div>
                <span className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Portfolio Task:</span>
                <ul className="space-y-1 pl-1">
                  {activeStep.portfolioTasks?.map((task, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="h-1.5 w-1.5 bg-emerald-400 rounded-full mt-1.5 shrink-0" />
                      {task}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* Box 3: Networking Actions */}
          <div className="glass-panel p-5 rounded-2xl space-y-3">
            <div className="flex items-center gap-2">
              <Mail className="h-4 w-4 text-purple-400" />
              <h4 className="heading-font text-sm font-bold text-white">Industry Connections</h4>
            </div>
            <ul className="space-y-2 text-xs text-slate-300 font-medium">
              {activeStep.networkingActions?.map((act, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="h-1.5 w-1.5 bg-purple-400 rounded-full mt-1.5 shrink-0" />
                  {act}
                </li>
              ))}
            </ul>
          </div>

          {/* Box 4: Interview Prep */}
          <div className="glass-panel p-5 rounded-2xl space-y-3">
            <div className="flex items-center gap-2">
              <Briefcase className="h-4 w-4 text-amber-400" />
              <h4 className="heading-font text-sm font-bold text-white">Assessment Alignment</h4>
            </div>
            <ul className="space-y-2 text-xs text-slate-300 font-medium">
              {activeStep.interviewPrep?.map((prep, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="h-1.5 w-1.5 bg-amber-400 rounded-full mt-1.5 shrink-0" />
                  {prep}
                </li>
              ))}
            </ul>
          </div>

        </div>

      </div>

    </div>
  );
}
